### ISSUE TITLE
2D array output ports only lists the first two sub-arrays.

### ISSUE THREAD

**Issue by mjcg91** [theRussetPotato/bifrost-output-reader#1]
I attached a screenshot for comparaison. I've trying with other data types and it seems like the issue is general.

Windows 10, Maya 2020.4, Bifrost 2.2.1.0

PS: I love this tool, it's a time saver! Thank you so much for this...

![image](https://user-images.githubusercontent.com/17196398/110981757-f7342200-83aa-11eb-8bfd-cb7f6acd0173.png)

**Comment by theRussetPotato** [comment]
@mjcg91 Yes I can replicate this same behavior. Thanks for reporting it in, I'll see what I can do to fix it.

**Comment by theRussetPotato** [comment]
@mjcg91 I updated the tool to display 2d arrays. Let me know if it's still causing an issue!

**Comment by mjcg91** [comment]
I can confirm the issue has been fixed. Thank you so much for the quick fix!
